### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by knightq** [knapo/jquery-inputmask-rails#2]
Please, change bad syntax:
 
    //= require jquery.inputmask.extensions
    //= require jquery.inputmask.date.extensions
    //= require jquery.inputmask.phone.extensions
    //= require jquery.inputmask.numeric.extensions
    //= require jquery.inputmask.regex.extensions

with 

    //= require inputmask.extensions
    //= require inputmask.date.extensions
    //= require inputmask.phone.extensions
    //= require inputmask.numeric.extensions
    //= require inputmask.regex.extensions

**Comment by knapo** [comment]
Done!

**Comment by flaviomestre** [comment]
I had issues with documentation too. The required includes was missing a line. This worked for me:

```
//= require inputmask
//= require jquery.inputmask
```

**Comment by knapo** [comment]
Fixed.
