### ISSUE TITLE
Acouldn't find file 'jquery.inputmask.extensions'

### ISSUE THREAD

**Issue by ssnake** [knapo/jquery-inputmask-rails#3]
After updating to latest version an app started to fail: 
ActionView::Template::Error: couldn't find file 'jquery.inputmask.extensions' with type 'application/javascript'

**Comment by ssnake** [comment]
sorry, didn't notice that I have to rename it 'jquery.inputmask.extensions' to 'inputmask.extensions'

**Comment by knapo** [comment]
exactly.

**Comment by sivapc** [comment]
Hello ,
I got this error, can you please help?
$ bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
Sprockets::FileNotFound: couldn't find file 'inputmask' with type 'application/javascript'
Checked in these paths
